name: Deploy Site

on:
  push:
    branches: [master]
    paths:
      - 'packages/fnx-ui/public/**'
      - 'packages/fnx-ui/site/**'
      - 'packages/fnx-ui/src/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Git Identity ğŸ”‘
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies â€ğŸŒˆ
        run: npm run bootstrap

      - name: Build Site â€ğŸ”¨
        run: npm run build:site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: packages/fnx-ui/dist-site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
