name: Deploy Site

on:
  push:
    branches: [master]
    paths:
      - 'packages/fnx-ui/site/**'
      - 'packages/fnx-ui/src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build Site
        run: npm run build:site

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          # Âú® Settings->Secrets ÈÖçÁΩÆ GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: gh-pages
          folder: packages/fnx-ui/dist-site
