name: Sync to Gitee

on:
  schedule:
    # æ¯å¤©åŒ—äº¬æ—¶é—´9ç‚¹è·‘
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee ğŸ›ï¸
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: https://github.com/Rockcookies/fnx-ui.git
          destination-repo: git@gitee.com:rockcookies/fnx-ui.git
